---
title: "C6 Data Anaylsis"
author: "Meg Raisle"
date: "November 15th, 2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tmaptools)
library(ggplot2)
library(here)
library(dplyr)
library(plotly)
library(wesanderson)
library(viridis)
library(grid)
library('knitr')
```

```{r readData, echo=FALSE}
c6time <- read.csv(here("c6anal/alldatac6times.csv"))

x_min <- as.POSIXct("2019-07-11 11:45:00")
x_max <- as.POSIXct("2019-07-19 12:59:00")

largernumbers <- element_text(face = "bold", size = 20)

#do basic plot of each 
plot <- ggplot(c6time)+
  geom_point(aes(x= DateTime, y= CDOM_ppb), color= "#27223c")
plot <- plot + theme(axis.text.y= largernumbers)


plot2 <- ggplot(c6time)+
  geom_point(aes(x= DateTime, y= Turbidity_NTU), color="#d1362f")

plot2 <- plot2 +theme(axis.text.y= largernumbers)



plot3 <- ggplot(c6time)+
  geom_point(aes(x= DateTime, y= Chlorophylla_ug.L), color="#2e604a")

plot3 <- plot3 + theme(axis.text.y= largernumbers)



plot4 <- ggplot(c6time)+
  geom_point(aes(x= DateTime, y= Phycocyanin_ppb), color="#dbb165")

plot4 <- plot4 + theme(axis.text.y= largernumbers)


````

## Plot of each of the C6 Metrics over time 
This data is at a 15 minute interval from the time period of July 11-July 19
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20, fig.height= 15}

grid.newpage()
grid.draw(rbind(ggplotGrob(plot), ggplotGrob(plot2), ggplotGrob(plot3), ggplotGrob(plot4)))

````

