---
title: "EOS Transects_Deltai_CH4"
author: "Meg Raisle"
date: "10/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tmaptools)
library(ggplot2)
library(here)
library(dplyr)
library(plotly)
library(wesanderson)
library(viridis)
library('knitr')
```

## Table for Each Day of EOS Transects 
```{r readData, echo=FALSE}
sumaug13 <- read.csv(here("Picarro/EOSTransects/081319/sumaug13_30sec_corrected.csv"))
sumjuly17 <- read.csv(here("Picarro/EOSTransects/071619/sumjuly17_30sec_corrected.csv"))
sumjuly23 <- read.csv(here("Picarro/EOSTransects/072219/sumjuly23_30sec_corrected.csv"))
sumjuly30 <- read.csv(here("Picarro/EOSTransects/072919/sumjuly30_30sec_corrected.csv"))
sumaug02 <- read.csv(here("Picarro/EOSTransects/080119/sumaug02_30sec_corrected.csv"))
sumaug09 <- read.csv(here("Picarro/EOSTransects/080819/sumaug09_30sec_corrected.csv"))

sumaug13$day <- as.character("Aug13")
sumjuly17$day <- as.character("July17")
sumjuly23$day <- as.character("July23")
sumjuly30$day <- as.character("July30")
sumaug02$day <- as.character("Aug02")
sumaug09$day <- as.character("Aug09")

sumalltransects <- rbind(sumaug13, sumjuly17, sumjuly23, sumjuly30, sumaug02, sumaug09)

sumaug13 <- sumaug13 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumaug02 <- sumaug02 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumaug09 <- sumaug09 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumjuly17 <- sumjuly17 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumjuly23 <- sumjuly23 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumjuly30 <- sumjuly30 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumjuly30 <- sumjuly30[c(1:8), ]

```

### July 16th Transects 
```{r data, eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20}

kable(sumjuly17, format = "markdown", row.names = FALSE)

```
### July 22nd Transects 
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20}

kable(sumjuly23, format = "markdown", row.names = FALSE)

```
### July 29th Transects 
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20}

kable(sumjuly30, format = "markdown", row.names = FALSE)

```
### August 1st Transects 
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20}

kable(sumaug02, format = "markdown", row.names = FALSE)

```
### August 8th Transects
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20}

kable(sumaug09, format = "markdown", row.names = FALSE)

```
### August 13th Transects
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20}

kable(sumaug13, format = "markdown", row.names = FALSE)

```
## All Delta_iCO2 30 Second Values Values 
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20, fig.height= 15}

#try doing it all together instead 

pbetter2 <- ggplot(sumalltransects, aes(x= Sample, y= CorrectedAverage, color=day))+
  geom_point(size=8)+
  xlab('Collar') +
  ylab('Delta30_Avg') +
  ggtitle("EOS Delta30 i_CO2 Corrected Summary") +
  scale_color_manual(values=wes_palette("Zissou1", n=6, type = c("continuous")))+
  theme(legend.position = "right")
pbetter2

```
There's alot of consistency in collars 5 and 6, hard to discern many other patterns just be looking at this. Wondering how we can incorporate rainfall into this?
