---
title: "Finding our Correction"
author: "Meg Raisle"
date: "10/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(wesanderson)
library('knitr')
```

```{r readData, echo=FALSE}
#import all data we want here

#bring in the linearity tables 
july15test <- read.csv(here("Picarro/Linearity/july15linearity.csv"), header = TRUE)
july15test$CHCorrection <- as.numeric("1.57")

aug09test <- read.csv(here("Picarro/Linearity/aug09linearity.csv"), header = TRUE)
aug09test$Correction <- as.numeric("1.22")

#bring in the combo table 

combocorrect<- read.csv(here("Picarro/EOSTransects/", "30secdailycorrections.csv"))

````

### Corrections Based on the Two Linearity Tests 
```{r data, eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20}
kable(july15test, format = "markdown")
kable(aug09test, format = "markdown")

````

### Final Table Correction 
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20}
kable(combocorrect, format = "markdown")

````
Feel pretty good about this other than August 9th. 