---
title: "Flux at Collar Transects"
author: "Chloe"
date: "Data from 8/1/2019 measurements

NOT THE RIGHT DATA YET"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Plots and Analysis
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(wesanderson)
library('knitr')

```

## Plots and Analysis

```{r readData, echo=FALSE}
#flux of synoptics 

date<- "08012019"


# eos2 data
eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_",date,".csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y %H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm..,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2",
                    "CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")


col1.4 <- eos2[2536:2539,]
col2.4 <- eos2[2532:2535,]
col3.4 <- eos2[2515:2517,]
col4.4 <- eos2[2544:2547,]
col5.4 <- eos2[2507:2510,]
col6.4 <- eos2[2511:2514,]
col7.4 <- eos2[2515:2517,]
col8.4 <- eos2[2520:2523,]

```


### Flux of Collars 

col1.4
```{r data, eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col1.4 <- select(col1.4,DateTime, Flux_eos2)
kable(head(col1.4), format = "markdown", row.names = FALSE)

```

col2.4
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col2.4 <- select(col2.4,DateTime, Flux_eos2)
kable(head(col2.4), format = "markdown", row.names = FALSE)

```
col3.4
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col3.4 <- select(col3.4,DateTime, Flux_eos2)
kable(head(col3.4), format = "markdown", row.names = FALSE)

```
col4.4
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col4.4 <- select(col4.4,DateTime, Flux_eos2)
kable(head(col4.4), format = "markdown", row.names = FALSE)

```
col5.4
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col5.4 <- select(col5.4,DateTime, Flux_eos2)
kable(head(col5.4), format = "markdown", row.names = FALSE)

```
col6.4
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col6.4 <- select(col6.4,DateTime, Flux_eos2)
kable(head(col6.4), format = "markdown", row.names = FALSE)

```
col7.4
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col7.4 <- select(col7.4,DateTime, Flux_eos2)
kable(head(col7.4), format = "markdown", row.names = FALSE)

```
col8.4
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col8.4 <- select(col8.4,DateTime, Flux_eos2)
kable(head(col8.4), format = "markdown", row.names = FALSE)

```
Average Flux of Each Site
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
col1.4avg <- mean(col1.4$Flux_eos2)
col2.4avg <- mean(col2.4$Flux_eos2)
col3.4avg <- mean(col3.4$Flux_eos2)
col4.4avg <- mean(col4.4$Flux_eos2)
col5.4avg <- mean(col5.4$Flux_eos2)
col6.4avg <- mean(col6.4$Flux_eos2)
col7.4avg <- mean(col7.4$Flux_eos2)
col8.4avg <- mean(col8.4$Flux_eos2)

col1.4sd <- sd(col1.4$Flux_eos2)
col2.4sd <- sd(col2.4$Flux_eos2)
col3.4sd <- sd(col3.4$Flux_eos2)
col4.4sd <- sd(col4.4$Flux_eos2)
col5.4sd <- sd(col5.4$Flux_eos2)
col6.4sd <- sd(col6.4$Flux_eos2)
col7.4sd <- sd(col7.4$Flux_eos2)
col8.4sd <- sd(col8.4$Flux_eos2)

a <- data.frame(AverageFlux = c(col1.4avg,col2.4avg,col3.4avg,col4.4avg,col5.4avg,col6.4avg,col7.4avg, col8.4avg))
rownames(a) <- c("col1.4", "col2.4", "col3.4", "col4.4", "col5.4", "col6.4", "col7.4", "col8.4")
kable(a, format = "markdown", row.names = TRUE)

sd <- data.frame(StdDev=
c(col1.4sd,col2.4sd,col3.4sd,col4.4sd,col5.4sd,col6.4sd,col7.4sd, col8.4sd))
rownames(sd) <- c("col1.4", "col2.4", "col3.4", "col4.4", "col5.4", "col6.4", "col7.4", "col8.4")
kable(sd, format = "markdown", row.names = TRUE)

a <- cbind(a,sd)

 
avgplot <- ggplot(a)+
 geom_errorbar(aes(x= 1:8,ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +
  geom_point(aes(x= 1:8, y= AverageFlux), color = "blue", size = 5)

avgplot <- avgplot + scale_x_continuous(breaks=1:8, labels=c("col1.4", "col2.4", "col3.4", "col4.4", "col5.4", "col6.4", "col7.4", "col8.4")) +
labs(x = "Collar", y = "Average FLux")
        

avgplot

```
