---
title: "Flux at Synoptic Points"
author: "Chloe"
date: "7/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Plots and Analysis
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(wesanderson)
library('knitr')

```

## Plots and Analysis

```{r readDatfa, echo=FALSE}
#flux of synoptics 

date<- "07182019"


# eos1 data
eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_",date,".csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y %H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm.,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2",
                    "CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")


# Subset data so only records at 5 minute intervals are retained
sub.1 <- subset(eos2, format(DateTime,'%OS')=='00')
sub.2 <- subset(sub.1, format(DateTime,'%M')%in% c("00","05","10","15","20","25","30","35","40","45","50","55","60"))
sub.2 <- sub.2[500:565,]
rownames(sub.2) <- NULL
#this above code is good

syn1 <- sub.2[2:6,]
syn5 <- sub.2[8:11,]
syn8 <- sub.2[13:17,]
syn8 <- syn8[which(syn8$Flux_eos2 > 0), ]
syn11 <- sub.2[19:22,]
syn14 <- sub.2[27:30,]
waterfall <- sub.2[36:39,]
syn20 <- sub.2[44:47,]
syn23 <- sub.2[50:53,]
syn29 <- sub.2[57:60,]
syn35 <- sub.2[63:66,]

```

### Flux over the 18th
```{r sub.2, eval=TRUE, warning=FALSE, echo=FALSE, fig.width=12}

plot <- ggplot(sub.2, aes(x = DateTime))+
  geom_line(aes(x= DateTime, y= Flux_eos2)) +
  labs(x = "Time", y = "Flux")

plot
```


### Flux of Synoptic Sites

Syn1
```{r data, eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn1 <- select(syn1,DateTime, Flux_eos2)
kable(head(syn1), format = "markdown", row.names = FALSE)

```
Syn5
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn5 <- select(syn5,DateTime, Flux_eos2)
kable(head(syn5), format = "markdown", row.names = FALSE)

```
Syn8
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn8 <- select(syn8,DateTime, Flux_eos2)
kable(head(syn8), format = "markdown", row.names = FALSE)

```
Syn11
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn11 <- select(syn11,DateTime, Flux_eos2)
kable(head(syn11), format = "markdown", row.names = FALSE)

```
Syn14
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn14 <- select(syn14,DateTime, Flux_eos2)
kable(head(syn14), format = "markdown", row.names = FALSE)

```
SynWaterfall
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

waterfall <- select(waterfall,DateTime, Flux_eos2)
kable(head(waterfall), format = "markdown", row.names = FALSE)

```
Syn20
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn20 <- select(syn20,DateTime, Flux_eos2)
kable(head(syn20), format = "markdown", row.names = FALSE)

```
Syn23
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn23 <- select(syn23,DateTime, Flux_eos2)
kable(head(syn23), format = "markdown", row.names = FALSE)

```
Syn29
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn29 <- select(syn29,DateTime, Flux_eos2)
kable(head(syn29), format = "markdown", row.names = FALSE)

```
Syn35
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn35 <- select(syn35,DateTime, Flux_eos2)
kable(head(syn35), format = "markdown", row.names = FALSE)

```

Average Flux of Each Site
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
syn1avg <- mean(syn1$Flux_eos2)
syn5avg <- mean(syn5$Flux_eos2)
syn8avg <- mean(syn8$Flux_eos2)
syn11avg <- mean(syn11$Flux_eos2)
syn14avg <- mean(syn14$Flux_eos2)
waterfallavg <- mean(waterfall$Flux_eos2)
syn20avg <- mean(syn20$Flux_eos2)
syn23avg <- mean(syn23$Flux_eos2)
syn29avg <- mean(syn29$Flux_eos2)
syn35avg <- mean(syn35$Flux_eos2)

syn1sd <- sd(syn1$Flux_eos2)
syn5sd <- sd(syn5$Flux_eos2)
syn8sd <- sd(syn8$Flux_eos2)
syn11sd <- sd(syn11$Flux_eos2)
syn14sd <- sd(syn14$Flux_eos2)
waterfallsd <- sd(waterfall$Flux_eos2)
syn20sd <- sd(syn20$Flux_eos2)
syn23sd <- sd(syn23$Flux_eos2)
syn29sd <- sd(syn29$Flux_eos2)
syn35sd <- sd(syn35$Flux_eos2)

a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, syn20avg, waterfallavg, syn14avg, syn11avg, syn8avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

 

kable(a, format = "markdown", row.names = TRUE) 

 

 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd, syn20sd, waterfallsd, syn14sd, syn11sd, syn8sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

kable(sd, format = "markdown", row.names = TRUE) 

 

a <- cbind(a,sd) 

 

avgplot <- ggplot(a)+ 

 geom_errorbar(aes(x= 1:10,ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +   

  geom_point(aes(x= 1:10, y= AverageFlux), color = "blue", size = 2)  

 

avgplot <- avgplot + scale_x_continuous(breaks=1:10, labels=c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1")) + 

labs(x = "Synoptic Site", y = "Average FLux") 

avgplot 

 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

dis20 <- 94.1 

waterfalldis <- 126 

dis14 <- 143.7 

dis11 <- 169.9 

dis8 <- 194.9 

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, dis20, waterfalldis, dis14, dis11, dis8, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

kable(dis, format = "markdown", row.names = TRUE) 

 

c <- cbind(a,dis) 

 

 

displot <- ggplot(c)+ 

 geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +   

  geom_point(aes(x= Distance, y= AverageFlux), color = "blue", size = 2) 

 

#displot <- displot + scale_x_continuous(breaks=1:10, labels=c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1")) + 

displot <- displot +  

  labs(x = "Synoptic Site Distance from Wetland (m)", y = "Average FLux (μmol/CO2/m2/s)") 

displot 

 

 

``` 