---
title: "Synoptics corrected Deltai_30seconds"
author: "Meg Raisle"
date: "11/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tmaptools)
library(ggplot2)
library(here)
library(dplyr)
library(plotly)
library(wesanderson)
library(viridis)
library('knitr')
```

## Table for Each Day of Synoptics
```{r readData, echo=FALSE}
sumaug13 <- read.csv(here("Picarro/synoptics/081219/sumaug13_30sec_corrected.csv"))
sumjuly19 <- read.csv(here("Picarro/synoptics/071819/sumjuly19_30sec_corrected.csv"))
sumaug02 <- read.csv(here("Picarro/synoptics/073119/sumaug02_30sec_corrected.csv"))
sumaug09 <- read.csv(here("Picarro/synoptics/080619/sumaug09_30sec_corrected.csv"))

sumaug13$day <- as.character("Aug12")
sumjuly19$day <- as.character("July18")
sumaug02$day <- as.character("July31")
sumaug09$day <- as.character("Aug06")

sumalltransects <- read.csv(here("Picarro/synoptics/synopticsrelativestreamdistance.csv"))

sumaug13 <- sumaug13 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumaug02 <- sumaug02 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumaug09 <- sumaug09 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)
sumjuly19 <- sumjuly19 %>%
  select(Sample, Avg_iCO2, StdDev_iCO2, Correction, CorrectedAverage)

largernumbers <- element_text(face = "bold", size = 20)
largernumbers2 <- element_text(face = "bold", size = 15)

```

### July 18th Synoptic 
```{r , eval=TRUE, warning=FALSE, echo=FALSE}

kable(sumjuly19, format = "markdown", row.names = FALSE)

plot1 <- ggplot(sumjuly19)+
  geom_point(aes(x=Sample, y=CorrectedAverage), color="purple", size=7)+
  labs(x="synoptic point", y="Delta_30s_Avg")+
  ggtitle("July 18th Synoptic Pull Averages")
plot1 <- plot1 + theme(axis.text.y= largernumbers, plot.title =largernumbers, axis.title.x = largernumbers2, axis.title.y = largernumbers2)

plot1


```


### July 31 Synoptic 
```{r , eval=TRUE, warning=FALSE, echo=FALSE}

kable(sumaug02, format = "markdown", row.names = FALSE)

plot2 <- ggplot(sumaug02)+
  geom_point(aes(x=Sample, y=CorrectedAverage), color="purple", size=7)+
  labs(x="synoptic point", y="Delta_30s_Avg")+
  ggtitle("July 31st Synoptic Pull Averages")
plot2 <- plot2 + theme(axis.text.y= largernumbers, plot.title =largernumbers, axis.title.x = largernumbers2, axis.title.y = largernumbers2)
plot2
```
### August 6th Synoptic 
```{r , eval=TRUE, warning=FALSE, echo=FALSE}

kable(sumaug09, format = "markdown", row.names = FALSE)

plot3 <- ggplot(sumaug09)+
  geom_point(aes(x=Sample, y=CorrectedAverage), color="purple", size=7)+
  labs(x="synoptic point", y="Delta_30s_Avg")+
  ggtitle("August 6th Synoptic Pull Averages")
plot3 <- plot3 + theme(axis.text.y= largernumbers, plot.title =largernumbers, axis.title.x = largernumbers2, axis.title.y = largernumbers2)
plot3
```
### August 12th Synoptic 
```{r , eval=TRUE, warning=FALSE, echo=FALSE}

kable(sumaug13, format = "markdown", row.names = FALSE)

plot4 <- ggplot(sumaug13)+
  geom_point(aes(x=Sample, y=CorrectedAverage), color="purple", size=7)+
  labs(x="synoptic point", y="Delta_30s_Avg")+
  ggtitle("August 12th Synoptic Pull Averages")
plot4 <- plot4 + theme(axis.text.y= largernumbers, plot.title =largernumbers, axis.title.x = largernumbers2, axis.title.y = largernumbers2)
plot4
```

## All Delta_iCO2 30 Second Values 
```{r , eval=TRUE, warning=FALSE, echo=FALSE}

#try doing it all together instead 

pbetter2 <- ggplot(sumalltransects, aes(x= Relativestreamdistance, y= CorrectedAverage, color=day))+
  geom_point(size=3)+
  xlab('Relative Stream Distance') +
  ylab('Delta30_Avg') +
  ggtitle("Synoptic Delta30 i_CO2 Corrected Summary") +
  scale_color_manual(values=wes_palette("Zissou1", n=4, type = c("continuous")))+
  theme(legend.position = "right")
pbetter2 <- pbetter2 + theme(axis.text.y= largernumbers, plot.title =largernumbers, axis.title.x = largernumbers2, axis.title.y = largernumbers2)
pbetter2

```

