---
title: "Flux at Collar Transects"
author: "Chloe"
date: "Data from 7/16/2019 measurements"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Plots and Analysis
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(wesanderson)
library('knitr')

```

## Plots and Analysis

```{r readData, echo=FALSE}
#flux of synoptics 

date<- "07182019"


# eos1 data
eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_",date,".csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y %H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm.,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2",
                    "CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")


# Subset data so only records at 5 minute intervals are retained
sub.1 <- subset(eos2, format(DateTime,'%OS')=='00')
sub.2 <- subset(sub.1, format(DateTime,'%M')%in% c("00","05","10","15","20","25","30","35","40","45","50","55","60"))

row.names(sub.2) <- NULL

col1.1 <- sub.2[434:439,]
col2.1 <- sub.2[442:446,]
col3.1 <- sub.2[451:455,]
col4.1 <- sub.2[460:464,]
col5.1 <- sub.2[471:475,]
col6.1 <- sub.2[479:484,]
col7.1 <- sub.2[487:493,]

```


Flux of Collars 7-16-2019

col1.1
```{r data, eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col1.1 <- select(col1.1,DateTime, Flux_eos2)
kable(head(col1.1), format = "markdown", row.names = FALSE)

```

col2.1
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col2.1 <- select(col2.1,DateTime, Flux_eos2)
kable(head(col2.1), format = "markdown", row.names = FALSE)

```
col3.1
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col3.1 <- select(col3.1,DateTime, Flux_eos2)
kable(head(col3.1), format = "markdown", row.names = FALSE)

```
col4.1
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col4.1 <- select(col4.1,DateTime, Flux_eos2)
kable(head(col4.1), format = "markdown", row.names = FALSE)

```
col5.1
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col5.1 <- select(col5.1,DateTime, Flux_eos2)
kable(head(col5.1), format = "markdown", row.names = FALSE)

```
col6.1
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col6.1 <- select(col6.1,DateTime, Flux_eos2)
kable(head(col6.1), format = "markdown", row.names = FALSE)

```
col7.1
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

col7.1 <- select(col7.1,DateTime, Flux_eos2)
kable(head(col7.1), format = "markdown", row.names = FALSE)

```

Average Flux of Each Site
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
col1.1avg <- mean(col1.1$Flux_eos2)
col2.1avg <- mean(col2.1$Flux_eos2)
col3.1avg <- mean(col3.1$Flux_eos2)
col4.1avg <- mean(col4.1$Flux_eos2)
col5.1avg <- mean(col5.1$Flux_eos2)
col6.1avg <- mean(col6.1$Flux_eos2)
col7.1avg <- mean(col7.1$Flux_eos2)

col1.1sd <- sd(col1.1$Flux_eos2)
col2.1sd <- sd(col2.1$Flux_eos2)
col3.1sd <- sd(col3.1$Flux_eos2)
col4.1sd <- sd(col4.1$Flux_eos2)
col5.1sd <- sd(col5.1$Flux_eos2)
col6.1sd <- sd(col6.1$Flux_eos2)
col7.1sd <- sd(col7.1$Flux_eos2)

a <- data.frame(AverageFlux = c(col1.1avg,col2.1avg,col3.1avg,col4.1avg,col5.1avg,col6.1avg,col7.1avg))
rownames(a) <- c("col1.1", "col2.1", "col3.1", "col4.1", "col5.1", "col6.1", "col7.1")
kable(a, format = "markdown", row.names = TRUE)

sd <- data.frame(StdDev=
c(col1.1sd,col2.1sd,col3.1sd,col4.1sd,col5.1sd,col6.1sd,col7.1sd))
rownames(sd) <- c("col1.1", "col2.1", "col3.1", "col4.1", "col5.1", "col6.1", "col7.1")
kable(sd, format = "markdown", row.names = TRUE)

a <- cbind(a,sd)

 
```

collars 7-16-2019
```{r data, eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
avgplot1 <- ggplot(a)+
 geom_errorbar(aes(x= 1:7,ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +
  geom_point(aes(x= 1:7, y= AverageFlux), color = "blue", size = 5)

avgplot1 <- avgplot1 + scale_x_continuous(breaks=1:7, labels=c("col1.1", "col2.1", "col3.1", "col4.1", "col5.1", "col6.1", "col7.1")) +
labs(x = "Collar", y = "Average FLux")
        

avgplot1

```



