---
title: "Flux at Synoptic Points"
author: "Chloe"
date: "7/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Plots and Analysis
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(wesanderson)
library('knitr')

```

## Plots and Analysis

```{r readData, echo=FALSE}
#flux of synoptics 

date<- "07292019"


# eos2 data
eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_",date,".csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y %H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm..,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2",
                    "CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")


# Subset data so only records at 5 minute intervals are retained
#sub.1 <- subset(eos2, format(DateTime,'%OS')=='00')
#sub.2 <- subset(sub.1, format(DateTime,'%M')%in% c("00","05","10","15","20","25","30","35","40","45","50","55","60"))

# eos1 data
eos1 <- read.csv(here("FieldData/EosFD","eos1_FIX_07312019.csv"))
#eos1$DateTime <- as.POSIXct(eos1$DateTime, format = "%m/%d/%Y %H:%M:%OS")
#eos2$dateTime <- as.POSIXct(as.character((eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y %H:%M:%OS")
# Subset data so only records at 5 minute intervals are retained
#sub.11 <- subset(eos1, format(DateTime,'%OS')=='00')
#sub.22 <- subset(sub.11, format(DateTime,'%M')%in% c("00","05","10","15","20","25","30","35","40","45","50","55","60"))


syn1 <- eos1[1854:1857,]
syn5 <- eos1[1860:1863,]
syn10 <- eos1[1871:1873,]
syn14 <- eos1[1879:1882,]
waterfall <- eos2[1158:1161,]
syn23 <- eos2[1169:1172,]
syn29 <- eos2[1175:1178,]
syn35 <- eos2[1180:1183,]

```

### Flux over the 18th
```{r eos2, eval=TRUE, warning=FALSE, echo=FALSE, fig.width=12}

plot <- ggplot(eos2, aes(x = DateTime))+
  geom_line(aes(x= DateTime, y= Flux_eos2)) +
  labs(x = "Time", y = "Flux")

plot
```


### Flux of Synoptic Sites

Syn1
```{r data, eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn1 <- select(syn1,DateTime, Flux_1)
kable(head(syn1), format = "markdown", row.names = FALSE)

```
Syn5
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn5 <- select(syn5,DateTime, Flux_1)
kable(head(syn5), format = "markdown", row.names = FALSE)

```
Syn10
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn10 <- select(syn10,DateTime, Flux_1)
kable(head(syn10), format = "markdown", row.names = FALSE)

```
Syn11
N/A Flow too fast for measure



Syn14
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn14 <- select(syn14,DateTime, Flux_1)
kable(head(syn14), format = "markdown", row.names = FALSE)

```
SynWaterfall
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

waterfall <- select(waterfall,DateTime, Flux_eos2)
kable(head(waterfall), format = "markdown", row.names = FALSE)

```
Syn20

N/A, flow too fast for measurement




Syn23
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn23 <- select(syn23,DateTime, Flux_eos2)
kable(head(syn23), format = "markdown", row.names = FALSE)

```
Syn29
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn29 <- select(syn29,DateTime, Flux_eos2)
kable(head(syn29), format = "markdown", row.names = FALSE)

```
Syn35
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}

syn35 <- select(syn35,DateTime, Flux_eos2)
kable(head(syn35), format = "markdown", row.names = FALSE)

```

Average Flux of Each Site
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
syn1avg <- mean(syn1$Flux_1)
syn5avg <- mean(syn5$Flux_1)
syn10avg <- mean(syn10$Flux_1)
syn14avg <- mean(syn14$Flux_1)
waterfallavg <- mean(waterfall$Flux_eos2)
syn23avg <- mean(syn23$Flux_eos2)
syn29avg <- mean(syn29$Flux_eos2)
syn35avg <- mean(syn35$Flux_eos2)

syn1sd <- sd(syn1$Flux_1)
syn5sd <- sd(syn5$Flux_1)
syn10sd<- sd(syn10$Flux_1)
syn14sd <- sd(syn14$Flux_1)
waterfallsd <- sd(waterfall$Flux_eos2)
syn23sd <- sd(syn23$Flux_eos2)
syn29sd <- sd(syn29$Flux_eos2)
syn35sd <- sd(syn35$Flux_eos2)

a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, waterfallavg, syn14avg, syn10avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "waterfall", "syn14", "syn10", "syn 5", "syn1") 

 

kable(a, format = "markdown", row.names = TRUE) 

 

 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd,  waterfallsd, syn14sd, syn10sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "waterfall", "syn14", "syn10", "syn 5", "syn1") 

kable(sd, format = "markdown", row.names = TRUE) 

 

a <- cbind(a,sd) 

 

avgplot <- ggplot(a)+ 

 geom_errorbar(aes(x= 1:8,ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +   

  geom_point(aes(x= 1:8, y= AverageFlux), color = "blue", size = 2)  

 

avgplot <- avgplot + scale_x_continuous(breaks=1:8, labels=c("syn35", "syn29", "syn23",  "waterfall", "syn14", "syn10", "syn 5", "syn1")) + 

labs(x = "Synoptic Site", y = "Average FLux") 

avgplot 

 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

waterfalldis <- 126 
dis14 <- 143.7 

dis10 <- 178.7

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, waterfalldis, dis14, dis10, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "waterfall", "syn14", "syn10", "syn 5", "syn1") 

kable(dis, format = "markdown", row.names = TRUE) 

 

c <- cbind(a,dis) 

 

 

displot <- ggplot(c)+ 

 geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +   

  geom_point(aes(x= Distance, y= AverageFlux), color = "blue", size = 2) 

 

#displot <- displot + scale_x_continuous(breaks=1:10, labels=c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1")) + 

displot <- displot +  

  labs(x = "Synoptic Site Distance from Wetland (m)", y = "Average FLux (μmol/CO2/m2/s)") 

displot 

 

 

``` 