--- 

title: "Flux at Synoptic Points" 

author: "Chloe" 

date: "8/12/2019" 

output: html_document 

--- 

 

```{r setup, include=FALSE} 

knitr::opts_chunk$set(echo = TRUE) 

# Plots and Analysis 

library(here) 

library(ggplot2) 

library(tidyr) 

library(dplyr) 

library(wesanderson) 

library('knitr') 
library(ggpubr)

 

``` 

 

## Plots and Analysis 

 

```{r readData2, echo=FALSE} 

#flux of synoptics  

 

date<- "08012019" 

eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_08142019.csv"))) 

eos2$Year <- paste0("20",eos2$Year) 

eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y%H:%M:%OS") 

eos2 <- eos2%>% 

  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm.., 

         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode) 

colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2","CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode") 

 

 

#eos2$Flux_eos2 <- as.numeric(eos2$Flux_eos2) 

eos2$Flux_eos2 <- as.numeric(as.character(eos2$Flux_eos2)) 

  

 

eos1 <- read.csv(here("FieldData/EosFD",paste0("eos1_08132019.1.csv"))) 

eos1$Year <- paste0("20",eos1$Year) 

eos1$dateTime <- as.POSIXct(as.character(paste0(eos1$Month,"/",eos1$Day,"/",eos1$Year," ",eos1$Time)), format = "%m/%d/%Y%H:%M:%OS") 

eos1 <- eos1%>% 

  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm., 

         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode) 

colnames(eos1) <- c("DateTime","Flux_eos1","Temp_C_eos1","CO2_Soil_ppm_eos1","CO2_Soil_STD_ppm_eos1","CO2_ATM_ppm_eos1","CO2_ATM_STD_ppm_eos1","Mode") 

 

syn1 <- eos2[3712:3715,] 

syn5 <- eos2[3717:3720,] 

syn8 <- eos2[3722:3725,] 

syn11 <- eos2[3728:3721,] 

syn14 <- eos2[3735:3738,] 

 

waterfall <- eos1[1229:1232,] 

syn20 <- eos1[1234:1237,] 

syn23 <- eos1[1239:1242,] 

syn29 <- eos1[1245:1248,] 

syn35 <- eos1[1250:1252,] 

 

``` 


Average Flux of Each Site 

```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12} 

syn1avg <- mean(syn1$Flux_eos2) 

syn5avg <- mean(syn5$Flux_eos2) 

syn8avg <- mean(syn8$Flux_eos2) 

syn11avg <- mean(syn11$Flux_eos2) 

syn14avg <- mean(syn14$Flux_eos2) 

waterfallavg <- mean(waterfall$Flux_eos1) 

syn20avg <- mean(syn20$Flux_eos1) 

syn23avg <- mean(syn23$Flux_eos1) 

syn29avg <- mean(syn29$Flux_eos1) 

syn35avg <- mean(syn35$Flux_eos1) 

 

syn1sd <- sd(syn1$Flux_eos2) 

syn5sd <- sd(syn5$Flux_eos2) 

syn8sd <- sd(syn8$Flux_eos2) 

syn11sd <- sd(syn11$Flux_eos2) 

syn14sd <- sd(syn14$Flux_eos2) 

waterfallsd <- sd(waterfall$Flux_eos1) 

syn20sd <- sd(syn20$Flux_eos1) 

syn23sd <- sd(syn23$Flux_eos1) 

syn29sd <- sd(syn29$Flux_eos1) 

syn35sd <- sd(syn35$Flux_eos1) 

 

a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, syn20avg, waterfallavg, syn14avg, syn11avg, syn8avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

 

kable(a, format = "markdown", row.names = TRUE) 

 

 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd, syn20sd, waterfallsd, syn14sd, syn11sd, syn8sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

kable(sd, format = "markdown", row.names = TRUE) 

 

a <- cbind(a,sd) 

 
 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

dis20 <- 94.1 

waterfalldis <- 126 

dis14 <- 143.7 

dis11 <- 169.9 

dis8 <- 194.9 

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, dis20, waterfalldis, dis14, dis11, dis8, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

kable(dis, format = "markdown", row.names = TRUE) 

 

c <- cbind(a,dis) 

 

 

displot12 <- ggplot(c)+ 

 geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="red") +   

  geom_point(aes(x= Distance, y= AverageFlux), color = "red", size = 2) + labs(x = "Synoptic Site Distance from Wetland (m)", y = "Average FLux (μmol/CO2/m2/s)")

displot12

 

 

``` 

```{r readDatas, echo=FALSE}
#flux of synoptics 

date<- "08012019"



eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_08142019.csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y%H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm..,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2","CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")


#eos2$Flux_eos2 <- as.numeric(eos2$Flux_eos2)
eos2$Flux_eos2 <- as.numeric(as.character(eos2$Flux_eos2))
 

eos1 <- read.csv(here("FieldData/EosFD",paste0("eos1_08132019.1.csv")))
eos1$Year <- paste0("20",eos1$Year)
eos1$dateTime <- as.POSIXct(as.character(paste0(eos1$Month,"/",eos1$Day,"/",eos1$Year," ",eos1$Time)), format = "%m/%d/%Y%H:%M:%OS")
eos1 <- eos1%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm.,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos1) <- c("DateTime","Flux_eos1","Temp_C_eos1","CO2_Soil_ppm_eos1","CO2_Soil_STD_ppm_eos1","CO2_ATM_ppm_eos1","CO2_ATM_STD_ppm_eos1","Mode")


syn1 <- eos1[546:549,]
syn5 <- eos1[551:454,]
syn8 <- eos1[556:559,]
syn11 <- eos1[561:564,]
syn14 <- eos1[567:570,]
waterfall <- eos2[3172:3175,]
syn20 <- eos2[3178:3181,]
syn23 <- eos2[3183:3186,]
syn29 <- eos2[3189:3192,]
syn35 <- eos2[3195:3198,]

```


Average Flux of Each Site
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
syn1avg <- mean(syn1$Flux_eos1)
syn5avg <- mean(syn5$Flux_eos1)
syn8avg <- mean(syn8$Flux_eos1)
syn11avg <- mean(syn11$Flux_eos1)
syn14avg <- mean(syn14$Flux_eos1)
waterfallavg <- mean(waterfall$Flux_eos2)
syn20avg <- mean(syn20$Flux_eos2)
syn23avg <- mean(syn23$Flux_eos2)
syn29avg <- mean(syn29$Flux_eos2)
syn35avg <- mean(syn35$Flux_eos2)

syn1sd <- sd(syn1$Flux_eos1)
syn5sd <- sd(syn5$Flux_eos1)
syn8sd <- sd(syn8$Flux_eos1)
syn11sd <- sd(syn11$Flux_eos1)
syn14sd <- sd(syn14$Flux_eos1)
waterfallsd <- sd(waterfall$Flux_eos2)
syn20sd <- sd(syn20$Flux_eos2)
syn23sd <- sd(syn23$Flux_eos2)
syn29sd <- sd(syn29$Flux_eos2)
syn35sd <- sd(syn35$Flux_eos2)
a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, syn20avg, waterfallavg, syn14avg, syn11avg, syn8avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

 

kable(a, format = "markdown", row.names = TRUE) 

 

 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd, syn20sd, waterfallsd, syn14sd, syn11sd, syn8sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

kable(sd, format = "markdown", row.names = TRUE) 

 

a <- cbind(a,sd) 

 


 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

dis20 <- 94.1 

waterfalldis <- 126 

dis14 <- 143.7 

dis11 <- 169.9 

dis8 <- 194.9 

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, dis20, waterfalldis, dis14, dis11, dis8, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

kable(dis, format = "markdown", row.names = TRUE) 

 

c <- cbind(a,dis) 

avgplot <- ggplot(c) +
  geom_point(aes(x= Distance, y= AverageFlux), color = "blue", size = 2)   +
   geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +   
labs(x = "Synoptic Site Distance from Wetland (m)", y = "Average FLux (μmol/CO2/m2/s)")
avgplot

combined1 <- displot12 + 
  geom_point(data = c, aes(x= Distance, y= AverageFlux), color = "blue", size = 2)   +
   geom_errorbar(data = c, aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="blue") +   labs(x = "Synoptic Site Distance from Wetland (m)", y = "Average FLux (μmol/CO2/m2/s)")

combined1






 

``` 
combine
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
displot <- ggarrange(displot12, avgplot)
displot

``` 

```{r readData, echo=FALSE}
date<- "08012019"




eos2 <- read.csv(here("FieldData/EosFD",paste0("eos2_",date,".csv")))
eos2$Year <- paste0("20",eos2$Year)
eos2$dateTime <- as.POSIXct(as.character(paste0(eos2$Month,"/",eos2$Day,"/",eos2$Year," ",eos2$Time)), format = "%m/%d/%Y%H:%M:%OS")
eos2 <- eos2%>%
  select(dateTime,Flux,Temperature..C.,CO2.Soil..ppm..,
         CO2.Soil.STD..ppm.,CO2.ATM..ppm.,CO2.ATM.STD..ppm.,Mode)
colnames(eos2) <- c("DateTime","Flux_eos2","Temp_C_eos2","CO2_Soil_ppm_eos2","CO2_Soil_STD_ppm_eos2","CO2_ATM_ppm_eos2","CO2_ATM_STD_ppm_eos2","Mode")

eos1 <- read.csv(here("FieldData/EosFD",paste0("eos1_FIX_07312019.csv")))
#eos1$Year <- paste0("20",eos1$Year)
#eos1$dateTime <- as.POSIXct(as.character(paste0(eos1$Month,"/",eos1$Day,"/",eos1$Year," ",eos1$Time)), format = "%m/%d/%Y %H:%M:%OS")
eos1 <- eos1%>%
  select(DateTime,Flux_1,Temp_C_1,CO2_Soil_1,
        CO2_Soil_STD_1,CO2_ATM_1,CO2_ATM_STD_1,Mode_1)
colnames(eos1) <- c("DateTime","Flux_eos1","Temp_C_eos1","CO2_Soil_ppm_eos1","CO2_Soil_STD_ppm_eos1","CO2_ATM_ppm_eos1","CO2_ATM_STD_ppm_eos1","Mode")



syn1 <- eos2[2177:2180,]
syn5 <- eos2[2183:2186,]
syn8 <- eos2[2188:2191,]
syn11 <- eos2[2193:2196,]
syn14 <- eos2[2200:2203,]
waterfall <- eos1[2534:2537,]
syn20 <- eos1[2540:2543,]
syn23 <- eos1[2546:2549,]
syn29 <- eos1[2552:2555,]
syn35 <- eos1[2557:2560,]

```

Average Flux of Each Site 7-31-2019
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
syn1avg <- mean(syn1$Flux_eos2)
syn5avg <- mean(syn5$Flux_eos2)
syn8avg <- mean(syn8$Flux_eos2)
syn11avg <- mean(syn11$Flux_eos2)
syn14avg <- mean(syn14$Flux_eos2)
waterfallavg <- mean(waterfall$Flux_eos1)
syn20avg <- mean(syn20$Flux_eos1)
syn23avg <- mean(syn23$Flux_eos1)
syn29avg <- mean(syn29$Flux_eos1)
syn35avg <- mean(syn35$Flux_eos1)

syn1sd <- sd(syn1$Flux_eos2)
syn5sd <- sd(syn5$Flux_eos2)
syn8sd <- sd(syn8$Flux_eos2)
syn11sd <- sd(syn11$Flux_eos2)
syn14sd <- sd(syn14$Flux_eos2)
waterfallsd <- sd(waterfall$Flux_eos1)
syn20sd <- sd(syn20$Flux_eos1)
syn23sd <- sd(syn23$Flux_eos1)
syn29sd <- sd(syn29$Flux_eos1)
syn35sd <- sd(syn35$Flux_eos1)


a <- data.frame(AverageFlux = c(syn35avg, syn29avg, syn23avg, syn20avg, waterfallavg, syn14avg, syn11avg, syn8avg, syn5avg, syn1avg)) 

rownames(a) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

 

kable(a, format = "markdown", row.names = TRUE) 

 

 

sd <- data.frame(StdDev= 

c(syn35sd, syn29sd, syn23sd, syn20sd, waterfallsd, syn14sd, syn11sd, syn8sd, syn5sd, syn1sd)) 

rownames(sd) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

kable(sd, format = "markdown", row.names = TRUE) 

 

a <- cbind(a,sd) 

 

dis35 <- 0 

dis29 <- 37.4 

dis23 <- 75.9 

dis20 <- 94.1 

waterfalldis <- 126 

dis14 <- 143.7 

dis11 <- 169.9 

dis8 <- 194.9 

dis5 <- 217.6 

dis1<- 245.2 

dis <- data.frame(Distance = c(dis35, dis29, dis23, dis20, waterfalldis, dis14, dis11, dis8, dis5, dis1)) 

rownames(dis) <- c("syn35", "syn29", "syn23", "syn20", "waterfall", "syn14", "syn11", "syn8", "syn 5", "syn1") 

kable(dis, format = "markdown", row.names = TRUE) 

 

c <- cbind(a,dis) 

 

displot31 <- ggplot(c) +

 geom_errorbar(aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="black") +   

  geom_point(aes(x= Distance, y= AverageFlux), color = "black", size = 2) + labs(x = "Synoptic Site Distance from Wetland (07-31-2019) (m)", y = "Average FLux (μmol/CO2/m2/s)") 

displot31
 

combined2 <- combined1 + 

 geom_errorbar(data = c, aes(x= Distance,y= AverageFlux, ymin= AverageFlux - StdDev, ymax= AverageFlux + StdDev), width=0.2, size=1, color="black") +   

  geom_point(data = c, aes(x= Distance, y= AverageFlux), color = "black", size = 2) + labs(x = "Synoptic Site Distance from Wetland (m)", y = "Average FLux (μmol/CO2/m2/s)") 

combined2



``` 
combine
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 12}
displot <- ggarrange(displot12, avgplot, displot31)
displot

``` 