---
title: "Preliminary C6 Data"
author: "Meg Raisle"
date: "November 9th, 2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tmaptools)
library(ggplot2)
library(here)
library(dplyr)
library(plotly)
library(wesanderson)
library(viridis)
library('knitr')
```

```{r readData, echo=FALSE}
c6 <- read.csv(here("data_4_analysis/c6.csv"))

#make posic.ct, posixct again
c6$DateTime <- as.POSIXct(c6$DateTime)


c6short <- c6[c(1:661), ]


````

## Plot of each of the C6 Metrics over time 
This data is at a 15 minute interval from the time period of July 11-July 19
```{r , eval=TRUE, warning=FALSE, echo=FALSE, fig.width = 20, fig.height= 15}

#let's try to make a simple plot 
plot <- ggplot(c6short)+
  geom_point(aes(x= DateTime, y= CDOM_ppb), color="blue")
ggplotly(plot)

plot2 <- ggplot(c6short)+
  geom_point(aes(x= DateTime, y= Turbidity_NTU), color="red")
ggplotly(plot2)

plot3 <- ggplot(c6short)+
  geom_point(aes(x= DateTime, y= Chlorophylla_ug.L), color="green")
ggplotly(plot3)

plot4 <- ggplot(c6short)+
  geom_point(aes(x= DateTime, y= Phycocyanin_ppb), color="purple")
ggplotly(plot4)

````


To-do: still need to connect this to time, continue working on fixing the 7/17 data, and discuss how to visualize depth and temperature. 
